name: iOS CI (CocoaPods)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Run Fastlane (Fake CD)
        run: fastlane build_only

      - name: Build & Test (No UITests)
        run: |
          xcodebuild clean test \
            -workspace CINewsCD.xcworkspace \
            -scheme CINewsCD \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -skip-testing:CINewsCDUITests \
            CODE_SIGNING_ALLOWED=NO
